### ISSUE TITLE
Nav Menu on the Website is completely broken

### ISSUE THREAD

**Issue by Dumbaz** [picsoung/speedhack#2]
With the way your nav menu works, all the links with the exception of the Home Button and the [Sponsors link](http://speedhack.io/sponsor) are broken on almost all of your pages. The sponsors link of course always works because of its format, the home button only working because it does work even without processing what it is supposed to do, which apparently is going to the #top of the page.

As an example, from the [Berlin supage](http://speedhack.io/events/berlin-speedhack), the About Button changes URL to http://speedhack.io/events/berlin-speedhack#about, changing absolutely nothing on site.

**Comment by picsoung** [comment]
Hey @Dumbaz thanks for your remark :)

I think I changed it couple of days ago, and now it should work fine.
Could you confirm?

Will you be attending SpeedHack in Berlin?

**Comment by Dumbaz** [comment]
I will try to be there, depends on me having free time. By the way, there are two different Tickets for the Speedhack event, one is capitalized the other is not, is only one of them correct, or are both?

Nav seems to be fixed, but I have not tested it thoroughly.

**Comment by picsoung** [comment]
They are both correct :) I guess we have a typo. Thanks for noticing it.

Would love to see you there, feel free to invite friends as well.
And let me know if you want to attend the conference too.
